spring:
  profiles: local
  datasource:
      url: jdbc:mysql://localhost:3306/gms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: 111111
logging:
  config: classpath:logback-local.xml


server:
  port:

